version: '3.12'

services:
  web:
    build: .
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py createsuperuser --username $DJANGO_SUPERUSER_USERNAME --email $DJANGO_SUPERUSER_EMAIL &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
