# Generated by Django 5.0.4 on 2024-04-21 22:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CL', 'Client'), ('EM', 'Employee'), ('SP', 'Supplier')], max_length=10)),
                ('balance', models.FloatField()),
                ('last_transaction', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PY', 'Payment (Supplier) +'), ('RV', 'Receivable (Supplier) -'), ('DB', 'Debt (Client) +'), ('CL', 'Collection (Client) -')], max_length=10)),
                ('account_after', models.FloatField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djaccman_app.account')),
            ],
        ),
    ]
